package org.example.sample2.domain.audience;

public enum AudienceCategory {
    CINEMACITIZEN_REGULAR,
    CINEMACITIZEN_OVER60,
    REGULAR,
    SENIOR,
    UNIVERSITY_STUDENT,
    HIGHSCHOOL_STUDENT,
    JUNIORHIGHSCHOOL_STUDENT,
    ELEMENTARYSCHOOL_STUDENT,
    HANDICAPPED_OVER_HIGHSCHOOL,
    HANDICAPPED_UNDER_HIGHSHCHOOL,
    UNKNOWN
}
